master:
  - {name: Oczekiwanie na element, initial: true,  value: Uruchomienie tasmy}
  - {name: Sprawdzenie rodzju elementu, initial: false,  value: Wykryto element}
  - {name: Oczekiwanie az element opusci tasme", initial: false,  value: Element duzy}
  - {name: Zatrzymanie tasmy, initial: false,  value: Element maly}
  - {name: Chwytanie elementu, initial: false,  value: Tasma zatrzymana}
  - {name: Umieszczenie elementu w pojemniku, initial: false,  value: Element chwycony}
  - {name: Ponowna proba chwycenia elementu", initial: false,  value: Element niechwycony}
  - {name: awaria, initial: false,  value: Element ponownie niechwycony}
slave:
  - {name: awaria, initial: true,  value: Wezwanie operatora}
  - {name: Usuwanie usterki, initial: false,  value: Usterka nieusunieta}
  - {name: Wylaczenie alarmu, initial: false,  value: Usterka usunieta}







