master:
  - {name: Oczekiwanie na element, initial: true,  value: Oczekiwanie na element}
  - {name: Sprawdzenie rodzju elementu, initial: false,  value: Sprawdzenie rodzju elementu}
  - {name: "Oczekiwanie az element opusci tasme", initial: false,  value: "Oczekiwanie az element opusci tasme"}
  - {name: "Zatrzymanie tasmy", initial: false,  value: "Zatrzymanie tasmy"}
  - {name: Chwytanie elementu, initial: false,  value: Chwycenie elementu}
  - {name: Umieszczenie elementu w pojemniku, initial: false,  value: Umieszczenie elementu w pojemniku}
  - {name: "Ponowna proba chwycenia elementu", initial: false,  value: "Ponowna proba chwycenia elementu"}
  - {name: awaria, initial: false,  value: awaria}
slave:
  - {name: awaria, initial: true,  value: awaria}
  - {name: Usuwanie usterki, initial: false,  value: Usuwanie usterki}
  - {name: "Wylaczenie alarmu", initial: false,  value: "Wylaczenie alarmu"}
